config/routes.rb
Cooking::Engine.routes.draw do
  resources :ingredients
  
  resources :recipes do
    member do
      get 'edit_description'
      patch 'edit_description', action: :update_description
    end
    resources :steps do
      collection do
        get 'reorder_steps'
        patch 'update_sequences'
      end
    end
    resources :quantified_ingredients
  end
  root :to => 'recipes#index'
end

app/models/cooking/base_model.rb
module Cooking
  class BaseModel < ActiveRecord::Base
    self.abstract_class = true
    ActiveRecord::Base.establish_connection Rails.configuration.database_configuration['cooking']
  end
end

app/models/cooking/ingredient.rb
module Cooking
  class Ingredient < ActiveRecord::Base
    has_many :recipes, :through=>:quantified_ingredients
    validates :name, presence:true
    #use IngredientImageUploader to upload image and store url to image column
    mount_uploader :image, IngredientImageUploader
  end
end

app/models/cooking/quantified_ingredient.rb
module Cooking
  class QuantifiedIngredient < ActiveRecord::Base
    # attr_accessible :title, :body
    belongs_to :recipe
    belongs_to :ingredient
    validates :quantity, presence:true
    accepts_nested_attributes_for :ingredient
  end
end

app/models/cooking/recipe.rb
module Cooking
  class Recipe < BaseModel
    set_table_name :recipes
    # attr_accessible :title, :body
    has_many :steps, :dependent=>:destroy
    has_many :quantified_ingredients
    has_many :ingredients, :through=>:quantified_ingredients
    accepts_nested_attributes_for :steps,:reject_if => lambda { |attrs| attrs.all? { |key, value| value.blank? }}
    accepts_nested_attributes_for :quantified_ingredients,:reject_if => lambda { |attrs| attrs.all? { |key, value| value.blank? }}
    #Use RecipeImageUploader to upload image and record path to image column
    mount_uploader :image, RecipeImageUploader
  end
end

app/models/cooking/step.rb
module Cooking
  class Step < ActiveRecord::Base
    # attr_accessible :title, :body
    belongs_to :recipe
    default_scope :order => 'sequence_number'
    before_create :set_sequence_number
    
    validates :description, presence:true
    #use StepImageUploader to upload image and store url to image column
    mount_uploader :image, StepImageUploader
  
protected
  
    def set_sequence_number
      if self.sequence_number.blank?
        self.sequence_number = self.recipe.steps.maximum('sequence_number').to_i + 1
      end
    end
  end
end

app/controllers/cooking/application_controller.rb
module Cooking
  class ApplicationController < ActionController::Base
    layout 'cooking/layouts/application'
  end
end

app/controllers/cooking/ingredients_controller.rb
require_dependency "cooking/application_controller"

module Cooking
  class IngredientsController < ApplicationController
    def create
      if not params[:recipe_id].blank?
        create_and_forward_to_recipe
      else
        create_and_go_back_to_show
      end
    end
    
    def destroy
      if not params[:recipe_id].blank?
        delete_and_forward_to_recipe
      else
        delete_and_go_back_to_index
      end
    end
private
    def delete_and_forward_to_recipe
      recipe = Recipe.find(params[:recipe_id])
      ingredient = Ingredient.find(params[:id])
      
      recipe.ingredients.delete(ingredient)#remove this ingredient from the current recipe
      if ingredient.recipes.blank? #no recipe use this ingredient
        ingredient.destroy
      end
  
      respond_to do |format|
        format.html { redirect_to edit_recipe_path(recipe) }
        format.json { head :ok }
      end
    end
  
    def delete_and_go_back_to_index
      ingredient = Ingredient.find(params[:id])
      if ingredient.recipes.blank? #no recipe use this ingredient
        ingredient.destroy
      else #this ingredient is in used somewhere
        notice = 'This ingredient is still in used, cant remove!'
      end
  
      respond_to do |format|
        format.html { redirect_to ingredients_path}
        format.json { head :ok }
      end
    end
  
    def create_and_forward_to_recipe
      @ingredient = Ingredient.new(params[:ingredient])
      recipe = Recipe.find(params[:recipe_id])
      @ingredient.recipes << recipe
  
      respond_to do |format|
        if @ingredient.save
          format.html { redirect_to edit_recipe_path(recipe), notice: 'An ingredient was successfully added.' }
          format.json { render json: @ingredient, status: :created, location: @ingredient }
        else
          format.html { render action: "new" }
          format.json { render json: @ingredient.errors, status: :unprocessable_entity }
        end
      end
    end
  
    def create_and_go_back_to_show
      @ingredient = Ingredient.new(params[:ingredient])
  
      respond_to do |format|
        if @ingredient.save
          format.html { redirect_to @ingredient, notice: 'An ingredient was successfully created.' }
          format.json { render json: @ingredient, status: :created, location: @ingredient }
        else
          format.html { render action: "new" }
          format.json { render json: @ingredient.errors, status: :unprocessable_entity }
        end
      end
    end
  end
end

app/controllers/cooking/quantified_ingredients_controller.rb
require_dependency "cooking/application_controller"

module Cooking
  class QuantifiedIngredientsController < ApplicationController
    before_action :find_recipe
    before_action :find_quantified_ingredient, only:[:destroy,:edit,:update]

    def new
      @quantified_ingredient = @recipe.quantified_ingredients.build
      @quantified_ingredient.ingredient = Ingredient.new
      respond_to do |format|
        format.js { render 'show_form' }
      end
    end

    def create
      @quantified_ingredient = QuantifiedIngredient.new(quantified_ingredient_params)
      @quantified_ingredient.recipe_id = params[:recipe_id]
      respond_to do |format|
        if @quantified_ingredient.save
          format.js { render 'reload_list_and_close_dialog'}
        else
          format.js { render 'show_form'}
        end
      end
    end
  
    def destroy
      respond_to do |format|
        if @quantified_ingredient.destroy
          format.js { render 'reload_list' }
        else
          flash[:alert] = "#{@quantified_ingredient.ingredient.name} cannot be removed"
          format.js { render 'show_dialog' }
        end
      end
    end

    def edit
      respond_to do |format|
        format.js {render 'show_form'}
      end
    end

    def update
      respond_to do |format|
        if @quantified_ingredient.update_attributes(quantified_ingredient_params)
          flash[:notice] = "#{@quantified_ingredient.ingredient.name} updated"
          format.js { render 'reload_list_and_update_dialog' }
        else
          format.js { render 'show_form' }
        end
      end
    end

    private

    def find_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end

    def find_quantified_ingredient
      @quantified_ingredient = @recipe.quantified_ingredients.find(params[:id])
    end

    def quantified_ingredient_params
      params.require(:quantified_ingredient)
            .permit(:quantity,
                    ingredient_attributes: [:name,:image])
    end
  end
end

app/controllers/cooking/recipes_controller.rb
require_dependency "cooking/application_controller"

module Cooking
  class RecipesController < ApplicationController
    set_tab :add, :recipe, only: %w(new)
    set_tab :edit, :recipe, only: %w(edit)
    set_tab :list, :recipe, only: %w(index)
    set_tab :show, :recipe, only: %w(show)

    before_action :find_recipe, only:[:destroy,:edit,:edit_description,:show,:update]

    # GET /recipes/1/edit_description.js
    def edit_description
      respond_to do |format|
        format.js { render 'show_form' }
      end
    end

    # GET /recipes
    def index
      @recipes = Recipe.all
      respond_to do |format|
        format.html
      end
    end

    # GET /recipes/1
    def show
      respond_to do |format|
        format.html
      end
    end

    # GET /recipes/new.js
    def new
      @recipe = Recipe.new
      respond_to do |format|
        format.js { render 'show_form' }
      end
    end
  
    # GET /recipes/1/edit
    def edit
      respond_to do |format|
        format.html
      end
    end
  
    # POST /recipes.js
    def create
      @recipe = Recipe.new(recipe_params)
      respond_to do |format|
        if @recipe.save
          flash[:notice] = 'New recipe created, time to add detail!'
          format.js { render js:"window.location='#{edit_recipe_path(@recipe)}'" }
        else
          format.html { render 'show_form' }
        end
      end
    end
  
    # PATCH /recipes/1.js
    def update
      respond_to do |format|
        if @recipe.update_attributes(recipe_params)
          flash[:notice] = "#{@recipe.name} updated"
          format.js { render 'show_dialog' }
        else
          format.js { render 'show_form' }
        end
      end
    end
  
    # DELETE /recipes/1.js
    def destroy
      respond_to do |format|
        if @recipe.destroy
          flash[:notice] = "#{@recipe.name} removed"
          format.js { render js:"window.location='#{recipes_path}'" }
        else
          flash[:alert] = "#{@recipe.name} can't be removed"
          format.js { render 'show_dialog' }
        end
      end
    end

    private

    def find_recipe
      @recipe = Recipe.find(params[:id])
    end

    def recipe_params
      params.require(:recipe)
            .permit(:name, :description, :image)
    end
  end
end

app/controllers/cooking/steps_controller.rb
require_dependency "cooking/application_controller"

module Cooking
  class StepsController < ApplicationController
    before_action :find_recipe
    before_action :find_step, only: [:show, :edit, :update, :destroy]

    # GET /recipes/1/steps
    def index
      @recipe = Recipe.find(params[:recipe_id])
      @steps = @recipe.steps.to_a

      respond_to do |format|
        format.html
      end
    end

    # GET /recipes/1/steps/new.js
    def new
      @step = @recipe.steps.build
      respond_to do |format|
        format.js {render 'show_form'}
      end
    end

    # GET /recipes/1/steps/2/edit.js
    def edit
      respond_to do |format|
        format.js {render 'show_form'}
      end
    end

    # POST /recipes/1/steps.js
    def create
      @step = @recipe.steps.build(step_params)

      respond_to do |format|
        if @step.save
          format.js {render 'reload_list_and_close_dialog'}
        else
          format.js {render 'show_form'}
        end
      end
    end

    # PATCH /recipes/1/steps/2.js
    def update
      respond_to do |format|
        if @step.update_attributes(step_params)
          flash[:notice] = "Step #{@step.sequence_number} updated"
          format.js {render 'reload_list_and_update_dialog'}
        else
          format.js {render 'show_form'}
        end
      end
    end

    # DELETE /recipes/1/steps/2.js
    def destroy
      respond_to do |format|
        if @step.destroy
          #TODO: re-sort all sequence numbers of steps
          format.js { render 'reload_list'}
        else
          flash[:alert] = "Cannot remove this step!"
          format.js { render 'show_dialog'}
        end
      end
    end

    # PATCH /cooking/recipes/14/steps/update_sequences.json
    def update_sequences
      respond_to do |format|
        begin
          Step.transaction do #update all or nothing
            params[:recordid].each_with_index do |id, index|
              Step.update_all("sequence_number = #{index + 1}", ["id = ?", id])
            end
          end
          format.json { head :ok }
        rescue Exception=>e
          notice = 'Cannot update sequence, there is something wrong, developer has been notified'
          format.json { head 400 }
        end
      end
    end

    private

    def step_params
      params.require(:step)
            .permit(:description, :image, :sequence_number)
    end

    def build_new_step
      #build a new step, this new one does not have sequence_id YET
      @step = @recipe.steps.build
    end

    def find_recipe
      @recipe = Recipe.find(params[:recipe_id])
    end

    def find_step
      @step = @recipe.steps.find(params[:id])
    end
  end
end

app/helpers/cooking/application_helper.rb
module Cooking
  class F5OffCanvasMenu < TabsOnRails::Tabs::Builder
    def add_raw(string)
      @tabs[:list] << @context.content_tag('li') do
        string
      end
    end

    def tab_for(tab, name, options, item_options = {})
      if current_tab?(tab)
        @tabs[:list] << @context.content_tag('li', class: @options[:active][:class]) do
          @context.link_to(name, '#')
        end
      else
        @tabs[:list] << @context.content_tag('li') do
          @context.link_to(name, options, item_options)
        end
      end
    end

    #How I want the list of tabs appear
    def build_tabs(options)
      output = ActiveSupport::SafeBuffer.new
      @tabs[:list].each do |link|
        output << link
      end
      return @context.content_tag('ul', options[:open_tabs]) do
        output.to_s
      end.to_s.html_safe
    end
  end

  class F5TopBarMenu < TabsOnRails::Tabs::Builder
    def add_raw(string)
      @tabs[:list] << string
    end

    def tab_for(tab, name, options, item_options = {})
      if current_tab?(tab)
        @tabs[:list] << @context.link_to(name, '#')
        @tabs[:current] = @tabs[:list].size - 1 #position of active link in the list
      else
        @tabs[:list] << @context.link_to(name, options, item_options)
      end
    end

    #How I want the list of tabs appear
    def build_tabs(options)
      output = ActiveSupport::SafeBuffer.new
      if @tabs[:current]
        output << @tabs[:list].delete_at(@tabs[:current])
      else#take the first tab and don't decorate it
        output << @tabs[:list].delete_at(0)
        @options[:active][:class] = ''
      end
      @options[:active][:class] = 'has-dropdown ' + @options[:active][:class] 

      idles = ActiveSupport::SafeBuffer.new
      @tabs[:list].each do |idle_link|
        idles << @context.content_tag('li') do
          idle_link
        end
      end

      output << @context.content_tag('ul', class: 'dropdown') do
        idles.to_s
      end
      return @context.content_tag('ul', options[:open_tabs]) do
        @context.content_tag('li', @options[:active]) do
          output.to_s
        end.to_s
      end.to_s.html_safe
    end
  end

  module ApplicationHelper
    def show_flash_message
      output = ''
      [:alert, :notice].each do |message|
        if flash[message]
          output = flash[message]
          flash.delete(message)
        end
      end
      return output
    end

    #Overide default image_tag to fall back to error image to avoid compiled blank image not found in production 
    def image_tag(source, options={})
      source = "cooking/image_not_available.png" if source.blank?
      super(source, options)
    end

    def random_image_version(imageable, base_version, max)
      version = "#{base_version}_#{Random.rand(max)}"
      return imageable.image_url(version.to_sym).to_s
    end
  end
end

app/views/cooking/recipes/_form.html.haml
=form_for(@recipe, html:{multipart:true}, remote:true) do |f|
  .row
    .large-12.columns
      =f.error_messages
  .row
    .large-12.columns
      =f.text_field :name, 'placeholder'=>'Name of recipe'
  .row
    .large-12.columns
      =f.text_area :description, 'placeholder'=>'description'
  .row
    .large-12.columns
      %label
        Cover image
        =f.file_field :image
        =f.text_field :remote_image_url, :placeholder => "or image URL"
  .row
    .large-6.columns
      %a.close-button-class.close-reveal-modal Cancel
    .large-6.columns
      =f.submit 'Done', class:'button expand'

app/views/cooking/recipes/edit.html.haml
-content_for(:page_js) do
  :javascript
    $(function() {
      $(".sortable_list").sortable({opacity: 0.6,
                                    cursor: 'move',
                                    update: function() {
                                      var order = $(this).sortable("serialize") + 
                                                  '&_method=PATCH';
                                      var update_url = '#{update_sequences_recipe_steps_url(@recipe)}';
                                      $.ajax({
                                          type: "POST",
                                          url: update_url,
                                          data: order,
                                          dataType: 'json'
                                      });
                                    }
                                  });
    });
.row
  .large-12.columns.text-center
    .center=image_tag @recipe.image_url(:medium_0).to_s
    =link_to "edit '#{@recipe.name}'", edit_description_recipe_path(@recipe),
             remote:true, class: 'button expand', 'data-reveal-id'=>'dialog'
    =hidden_field_tag :recipe_id, @recipe.id
.row
  .large-6.columns
    &nbsp;
.row
  .large-6.columns
    %label
      Drag the steps to reorder their sequence
    %ol.sortable_list#steps
      =render partial:'cooking/steps/list'
  .large-6.columns
    %label
      Ingredient can not be reordered
    %ul#ingredients
      =render partial:'cooking/quantified_ingredients/list'

app/views/cooking/recipes/edit_description.js.erb
$('#dialog').html("<%= escape_javascript(render partial:'cooking/recipes/form') %>");

app/views/cooking/recipes/form.js.erb
$('#dialog').html("<%= escape_javascript(render partial:'cooking/recipes/form') %>");

app/views/cooking/recipes/index.html.haml
-content_for(:page_js) do
  :javascript
    $(document).ready(function(){
      var $container = $('#recipes');
      // initialize
      $container.imagesLoaded( function() {
        $container.masonry({
          columnWidth: 200,
          gutter: 20,
          itemSelector: '.recipe'
        });
      });
    });

#recipes
  -@recipes.each do |recipe|
    .recipe
      .img=link_to image_tag(random_image_version(recipe, 'medium', 3)), recipe
      .txt
        =link_to recipe.name, recipe
        %br
        =truncate(recipe.description, length:30)

app/views/cooking/recipes/show.html.haml
-content_for(:nav_title) do
  %a{href:'#','data-dropdown'=>'cover'}
    =truncate(@recipe.name, length:15)

#cover{class:'[tiny small medium large content] f-dropdown content', 'data-dropdown-content'=>true}
  %h1=@recipe.name
  %p=@recipe.description
  =image_tag(@recipe.image_url(:medium_2).to_s)

#steps
  .row
    .large-12.columns.text-center
      %button.button{'data-swapout'=>'#steps', 'data-swapin'=>'#ingredients'} Ingredients
  .row
    .large-12.columns.text-center
      %ul{'data-orbit'=>true,
          'data-options'=>'pause_on_hover:true;slide_number:false;circular:false;variable_height:true'}
        -@recipe.steps.each_with_index do |step, index|
          %li
            =image_tag(step.image_url(:medium_1).to_s)
            .orbit-caption="#{step.sequence_number}. #{step.description}"
#ingredients.hide
  .row
    .large-12.columns.text-center
      %button.button{'data-swapin'=>'#steps', 'data-swapout'=>'#ingredients'} Steps
  .row
    .large-12.columns.text-center
      %ul.clearing-thumbs{'data-clearing'=>true}
        -@recipe.quantified_ingredients.each_with_index do |q, index|
          %li
            %a{'href'=>asset_path(q.ingredient.image_url(:medium_1).to_s)}
              =image_tag(q.ingredient.image_url(:medium_1).to_s,
                         'data-caption'=>"#{q.quantity} #{q.ingredient.name}")

app/views/cooking/recipes/show_dialog.js.erb
$('#dialog').html("<%= escape_javascript(show_flash_message) %>");

app/views/cooking/recipes/show_form.js.erb
$('#dialog').html("<%= escape_javascript(render partial:'cooking/recipes/form') %>");